# joint_limits.yaml
joint_limits:
  fr3_joint1:
    has_velocity_limits: true
    max_velocity: 2.1750
    has_acceleration_limits: true
    max_acceleration: 15.0
  fr3_joint2:
    has_velocity_limits: true
    max_velocity: 2.1750
    has_acceleration_limits: true
    max_acceleration: 7.5
  fr3_joint3:
    has_velocity_limits: true
    max_velocity: 2.1750
    has_acceleration_limits: true
    max_acceleration: 10.0
  fr3_joint4:
    has_velocity_limits: true
    max_velocity: 2.1750
    has_acceleration_limits: true
    max_acceleration: 12.5
  fr3_joint5:
    has_velocity_limits: true
    max_velocity: 2.6100
    has_acceleration_limits: true
    max_acceleration: 15.0
  fr3_joint6:
    has_velocity_limits: true
    max_velocity: 2.6100
    has_acceleration_limits: true
    max_acceleration: 20.0
  fr3_joint7:
    has_velocity_limits: true
    max_velocity: 2.6100
    has_acceleration_limits: true
    max_acceleration: 20.0
